CREATE TABLE MANAGES(
	Book_Quantity INT,
	BookID INT,
	EmployeeID INT,
	Notification BOOLEAN GENERATED ALWAYS AS (Book_Quantity < 5) STORED,
	FOREIGN KEY (BookID) REFERENCES INVENTORY(BookID),
	FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);
