CREATE TABLE PAYMENT(
	PaymentID INT NOT NULL,
	Payment_Method VARCHAR(15),
	Payment_Date DATE,
	Payment_Amount DECIMAL(10,2),
	OrderID INT,
	FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
	PRIMARY KEY (PaymentID)
);
ALTER TABLE ORDERS
ADD CONSTRAINT fk_O_P
FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID);
