\source .\createdatabase.sql
\source .\customer.sql
\source .\employee.sql
\source .\book.sql
\source .\author.sql
\source .\order.sql
\source .\payment.sql
\source .\inventory.sql
\source .\assists.sql
\source .\manages.sql
\source .\tracks.sql
\source .\writes.sql
\source .\contains.sql
